### ISSUE TITLE
how to migrate to  withTracker

### ISSUE THREAD

**Issue by ketankulkarni** [inProgress-team/react-native-meteor#311]
I have been using createContainer but now I want to migrate to withTracker. From the documentation I used Tracker

```
import Meteor, { Tracker } from "react-native-meteor";
export default Tracker(() => {
  Meteor.subscribe("showCredit");
  return {
    credit:
      Meteor.collection("credit").find(
        {},
        { sort: { createdAt: -1 }, limit: 5 }
      ) || []
  };
}, SendMoney);

```
output - 
(0, _reactnativeMeteor.Tracker) is not a function

**Comment by charpeni** [comment]
I'm not sure how `Tracker` or even `composeWithTracker` works, but i'm sure this won't work out of the box as [`withTracker`](https://guide.meteor.com/react.html#using-withTracker).

I'll be also interested to migrate to `withTracker` instead of the deprecated `createContainer`, unfortunately I can't check this right now. Let me know if you find a solution before I do.

**Comment by ketankulkarni** [comment]
@charpeni sure

**Comment by charpeni** [comment]
`withTracker` was introduced in #313 and is now available in `react-native-meteor@1.3.0`. :tada:
